export const dynamic = "force-dynamic";
import { NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { withAuth, verifyTenantResource } from '@/lib/api-auth';
import { ROLES } from '@/lib/roles';

export const GET = withAuth([ROLES.AUDITOR, ROLES.CFO], async (req, { params }, auth) => {
  await verifyTenantResource(auth.supabase, 'investigations', params.id, auth.companyId);

  const { data: inv, error } = await auth.supabase
    .from('investigations')
    .select('*, vendors(*), wire_requests(*, clerk:clerk_id(full_name, email), cfo:cfo_id(full_name, email)), users!assigned_to(full_name), investigation_notes(*, users!author_id(full_name, role))')
    .eq('id', params.id)
    .single();

  if (error || !inv) return NextResponse.json({ error: 'Case not found' }, { status: 404 });

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  doc.fontSize(18).fillColor('#0f172a').text('ClearWire Compliance Case File', { align: 'left' });
  doc.fontSize(10).fillColor('#64748b').text(`Case ${inv.case_number} — Generated ${new Date().toLocaleString()}`);
  doc.moveDown(1.5);

  doc.fontSize(13).fillColor('#0f172a').text('Case Summary');
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#334155');
  doc.text(`Status: ${inv.status}`);
  doc.text(`Type: ${inv.wire_id ? 'Wire Fraud' : 'Vendor Anomaly'}`);
  doc.text(`Risk Score: ${inv.risk_score ?? 'N/A'} / 100`);
  doc.text(`Opened: ${new Date(inv.created_at).toLocaleString()}`);
  if (inv.resolved_at) doc.text(`Resolved: ${new Date(inv.resolved_at).toLocaleString()}`);
  doc.moveDown(1);

  if (inv.wire_requests) {
    doc.fontSize(13).fillColor('#0f172a').text('Segregation of Duties — Chain of Custody');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#334155');
    doc.text(`Wire Amount: $${Number(inv.wire_requests.amount).toLocaleString()}`);
    doc.text(`Vendor: ${inv.wire_requests.vendor_name_snapshot}`);
    doc.text(`Initiated by: ${inv.wire_requests.clerk?.full_name || 'Unknown'} (${inv.wire_requests.clerk?.email || ''})`);
    if (inv.wire_requests.cfo) doc.text(`Actioned by: ${inv.wire_requests.cfo?.full_name} (${inv.wire_requests.cfo?.email})`);
    if (inv.wire_requests.cryptographic_hash) {
      doc.moveDown(0.3);
      doc.fontSize(8).fillColor('#94a3b8').text(`Cryptographic Signature: ${inv.wire_requests.cryptographic_hash}`);
    }
    doc.moveDown(1);
  }

  if (inv.vendors) {
    doc.fontSize(13).fillColor('#0f172a').text('Vendor Details');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#334155');
    doc.text(`Name: ${inv.vendors.name}`);
    doc.text(`Status: ${inv.vendors.status}`);
    doc.moveDown(1);
  }

  doc.fontSize(13).fillColor('#0f172a').text('Investigation Notes');
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor('#334155');
  if (!inv.investigation_notes || inv.investigation_notes.length === 0) {
    doc.text('No notes recorded.');
  } else {
    inv.investigation_notes.forEach((n: any) => {
      doc.fontSize(9).fillColor('#64748b').text(`${new Date(n.created_at).toLocaleString()} — ${n.users?.full_name || 'Unknown'} (${n.users?.role || ''})`);
      doc.fontSize(10).fillColor('#334155').text(n.note);
      doc.moveDown(0.5);
    });
  }
  doc.moveDown(1);

  if (inv.status === 'resolved') {
    doc.fontSize(13).fillColor('#0f172a').text('Resolution');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#334155').text(inv.resolution_notes || 'No resolution notes provided.');
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#94a3b8').text('Generated by ClearWire — this document reflects the immutable audit trail as of the generation timestamp above.', { align: 'center' });

  doc.end();
  const pdfBuffer = await done;

  return new NextResponse(pdfBuffer, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="case-${inv.case_number}.pdf"`,
    },
  });
});
