export const dynamic = "force-dynamic";
import { NextResponse } from 'next/server';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { withAuth, verifyTenantResource } from '@/lib/api-auth';
import { ROLES } from '@/lib/roles';

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const MAX_WIDTH = PAGE_WIDTH - MARGIN * 2;

function wrapText(text: string, font: any, size: number, maxWidth: number): string[] {
  const words = String(text ?? '').split(/\s+/);
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(test, size) > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export const GET = withAuth([ROLES.AUDITOR, ROLES.CFO], async (req, { params }, auth) => {
  await verifyTenantResource(auth.supabase, 'investigations', params.id, auth.companyId);

  const { data: inv, error } = await auth.supabase
    .from('investigations')
    .select('*, vendors(*), wire_requests(*, clerk:clerk_id(full_name, email), cfo:cfo_id(full_name, email)), users!assigned_to(full_name), investigation_notes(*, users!author_id(full_name, role))')
    .eq('id', params.id)
    .single();

  if (error || !inv) return NextResponse.json({ error: 'Case not found' }, { status: 404 });

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT - MARGIN;

  const dark = rgb(0.06, 0.09, 0.16);
  const gray = rgb(0.4, 0.46, 0.55);
  const lightGray = rgb(0.58, 0.64, 0.72);

  function ensureSpace(needed: number) {
    if (y - needed < MARGIN) {
      page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      y = PAGE_HEIGHT - MARGIN;
    }
  }

  function heading(text: string) {
    ensureSpace(30);
    page.drawText(text, { x: MARGIN, y, size: 13, font: bold, color: dark });
    y -= 20;
  }

  function line(text: string, opts: { size?: number; color?: any; f?: any } = {}) {
    const size = opts.size ?? 10;
    const f = opts.f ?? font;
    const color = opts.color ?? rgb(0.2, 0.25, 0.33);
    const wrapped = wrapText(text, f, size, MAX_WIDTH);
    for (const l of wrapped) {
      ensureSpace(size + 6);
      page.drawText(l, { x: MARGIN, y, size, font: f, color });
      y -= size + 6;
    }
  }

  page.drawText('ClearWire Compliance Case File', { x: MARGIN, y, size: 18, font: bold, color: dark });
  y -= 22;
  line(`Case ${inv.case_number} — Generated ${new Date().toLocaleString()}`, { size: 9, color: lightGray });
  y -= 12;

  heading('Case Summary');
  line(`Status: ${inv.status}`);
  line(`Type: ${inv.wire_id ? 'Wire Fraud' : 'Vendor Anomaly'}`);
  line(`Risk Score: ${inv.risk_score ?? 'N/A'} / 100`);
  line(`Opened: ${new Date(inv.created_at).toLocaleString()}`);
  if (inv.resolved_at) line(`Resolved: ${new Date(inv.resolved_at).toLocaleString()}`);
  y -= 10;

  if (inv.wire_requests) {
    heading('Segregation of Duties — Chain of Custody');
    line(`Wire Amount: $${Number(inv.wire_requests.amount).toLocaleString()}`);
    line(`Vendor: ${inv.wire_requests.vendor_name_snapshot}`);
    line(`Initiated by: ${inv.wire_requests.clerk?.full_name || 'Unknown'} (${inv.wire_requests.clerk?.email || ''})`);
    if (inv.wire_requests.cfo) line(`Actioned by: ${inv.wire_requests.cfo?.full_name} (${inv.wire_requests.cfo?.email})`);
    if (inv.wire_requests.cryptographic_hash) {
      y -= 4;
      line(`Cryptographic Signature: ${inv.wire_requests.cryptographic_hash}`, { size: 7, color: lightGray });
    }
    y -= 10;
  }

  if (inv.vendors) {
    heading('Vendor Details');
    line(`Name: ${inv.vendors.name}`);
    line(`Status: ${inv.vendors.status}`);
    y -= 10;
  }

  heading('Investigation Notes');
  if (!inv.investigation_notes || inv.investigation_notes.length === 0) {
    line('No notes recorded.');
  } else {
    for (const n of inv.investigation_notes) {
      line(`${new Date(n.created_at).toLocaleString()} — ${n.users?.full_name || 'Unknown'} (${n.users?.role || ''})`, { size: 8, color: lightGray });
      line(n.note);
      y -= 6;
    }
  }
  y -= 10;

  if (inv.status === 'resolved') {
    heading('Resolution');
    line(inv.resolution_notes || 'No resolution notes provided.');
  }

  ensureSpace(30);
  y -= 10;
  page.drawText('Generated by ClearWire — reflects the immutable audit trail as of the timestamp above.', { x: MARGIN, y, size: 7, font, color: lightGray });

  const pdfBytes = await pdfDoc.save();

  return new NextResponse(Buffer.from(pdfBytes), {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="case-${inv.case_number}.pdf"`,
    },
  });
});