import { NextResponse } from 'next/server';
import { withAuth, verifyTenantResource } from '@/lib/api-auth';
import { ROLE_VALUES } from '@/lib/roles';

export const GET = withAuth([...ROLE_VALUES], async (req, { params }, auth) => {
  await verifyTenantResource(auth.supabase, 'wire_requests', params.id, auth.companyId);

  const { data, error } = await auth.supabase
    .from('wire_requests')
    .select('*')
    .eq('id', params.id)
    .single();

  if (error || !data) return new NextResponse('Wire not found', { status: 404 });

  const htmlContent = `
    <html>
      <head>
        <title>ClearWire Certificate - ${data.id}</title>
        <style>
          body { font-family: 'Courier New', Courier, monospace; padding: 40px; color: #1e293b; }
          .header { border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px; }
          h1 { color: #0f172a; font-size: 24px; margin: 0; }
          .status { color: ${data.status === 'approved' ? '#059669' : '#dc2626'}; font-weight: bold; font-size: 18px; margin-top: 10px; text-transform: uppercase; }
          .row { margin-bottom: 15px; display: flex; }
          .label { font-weight: bold; width: 200px; color: #64748b; }
          .value { flex: 1; }
          .hash-box { background: #f8fafc; border: 1px solid #cbd5e1; padding: 15px; margin-top: 30px; word-break: break-all; font-size: 12px; }
          .footer { margin-top: 50px; font-size: 12px; color: #94a3b8; text-align: center; }
          @media print { body { padding: 0; } }
        </style>
      </head>
      <body onload="window.print()">
        <div class="header">
          <h1>CLEARWIRE SECURE AUDIT LOG</h1>
          <div class="status">STATUS: ${data.status}</div>
        </div>
        
        <div class="row"><div class="label">Transaction ID:</div><div class="value">${data.id}</div></div>
        <div class="row"><div class="label">Vendor Name:</div><div class="value">${data.vendor_name_snapshot}</div></div>
        <div class="row"><div class="label">Amount (USD):</div><div class="value">$${Number(data.amount).toLocaleString()}</div></div>
        <div class="row"><div class="label">Purpose:</div><div class="value">${data.purpose || 'N/A'}</div></div>
        <div class="row"><div class="label">Requested At:</div><div class="value">${new Date(data.created_at).toLocaleString()}</div></div>
        
        ${data.status === 'approved' ? `
          <div class="row"><div class="label">Actioned At:</div><div class="value">${new Date(data.approved_at).toLocaleString()}</div></div>
          <div class="row"><div class="label">Auth Method:</div><div class="value">Out-of-band Biometric (WebAuthn/FIDO2)</div></div>
          <div class="hash-box">
            <strong>CRYPTOGRAPHIC SIGNATURE HASH:</strong><br/>
            ${data.cryptographic_hash}
            <br/><br/>
            <em>This hash mathematically verifies that the trusted executive device authorized this specific transaction amount and destination.</em>
          </div>
        ` : ''}

        <div class="footer">Generated by ClearWire Security - Immunizing B2B Payments Against Deepfakes</div>
      </body>
    </html>
  `;

  return new NextResponse(htmlContent, { headers: { 'Content-Type': 'text/html' } });
});
